name: dart_dartrix
description: Dartrix template plugin package.  Contains templates for Dart apps, libraries, packages, etc.
homepage: https://github.com/mobileink/dart_dartrix
version: 0.1.2-beta

dependencies:
  args: ^1.5.3

dartrix:
  version: 0.1.20-alpha

environment:
  sdk: '>=2.6.0 <3.0.0'

